[package]
name = "degreepath-auditor"
version = "0.1.0"
authors = ["Hawken Rives <hawkrives@fastmail.fm>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
decorum = { version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
void = { version = "1.0" }

[dev-dependencies]
globwalk = "0.7"
insta = "0.7"
maplit = "1.0"
pretty_assertions = "0.6"
rayon = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"

[[example]]
name = "parser"
path = "examples/parser.rs"

[[example]]
name = "printer"
path = "examples/printer.rs"

[[example]]
name = "snapshot"
path = "examples/snapshot.rs"

[[example]]
name = "auditor"
path = "examples/auditor.rs"
